# Generated by Django 4.0.3 on 2022-03-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_active_company_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('is_active', 'name', 'contract_number')},
        ),
    ]
