# Generated by Django 4.0.3 on 2022-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
