# Generated by Django 4.0.3 on 2022-03-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('update_time', 'is_active', 'name', 'contract_number')},
        ),
    ]
