# Generated by Django 4.0.3 on 2022-03-29 14:53

from django.db import migrations, models
import srproj.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[srproj.common.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[srproj.common.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[srproj.common.validators.validate_phone]),
        ),
    ]
