# Generated by Django 4.0.3 on 2022-04-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_accountprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='is_restricted',
        ),
    ]
