# Generated by Django 4.0.3 on 2022-04-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('update_time', 'is_active', 'name', 'contract_number'), 'verbose_name_plural': 'companies'},
        ),
    ]
