# Generated by Django 4.0.3 on 2022-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_productfamily_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Process', 'In Process'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.DeleteModel(
            name='TicketPhase',
        ),
    ]
