# Generated by Django 4.0.3 on 2022-03-18 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_alter_ticketassessment_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='modifier', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='register_date',
            field=models.DateTimeField(),
        ),
    ]
