# Generated by Django 4.0.3 on 2022-03-18 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0008_ticket_modifier_alter_ticket_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketworkflow',
            name='typ',
            field=models.CharField(choices=[('Customer Note', 'Customer Note'), ('RCA', 'RCA'), ('Support Note', 'Support Note'), ('Resolution', 'Resolution')], default='RCA', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketeventlog',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketeventlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketfiles',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
