# Generated by Django 4.0.3 on 2022-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketworkflow_typ_alter_ticketeventlog_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketworkflow',
            old_name='owner',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='ticketworkflow',
            name='typ',
            field=models.CharField(choices=[('Note', 'Note'), ('RCA', 'RCA'), ('Corrective Action', 'Corrective Action'), ('Resolution', 'Resolution')], max_length=17),
        ),
    ]
