# Generated by Django 4.0.3 on 2022-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_rename_event_creator_ticketassessment_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticketassessment',
            name='overall',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Poor', 'Poor'), ('Fair', 'Fair')], max_length=9),
        ),
        migrations.AlterField(
            model_name='ticketassessment',
            name='reaction',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Poor', 'Poor'), ('Fair', 'Fair')], max_length=9),
        ),
        migrations.AlterField(
            model_name='ticketassessment',
            name='resolve',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Poor', 'Poor'), ('Fair', 'Fair')], max_length=9),
        ),
    ]
