# Generated by Django 4.0.3 on 2022-03-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_active_alter_ticketassessment_overall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='active',
            new_name='is_active',
        ),
    ]
