# Generated by Django 4.0.3 on 2022-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_rename_active_ticket_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Process', 'In Process'), ('Solution Provided', 'Solution Provided'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=17),
        ),
    ]
