# Generated by Django 4.0.3 on 2022-03-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketassessment',
            options={'ordering': ('-event_time',)},
        ),
    ]
