# Generated by Django 4.0.3 on 2022-03-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticketassessment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.productfamily'),
        ),
    ]
