# Generated by Django 4.0.3 on 2022-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_product_is_active_alter_product_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
