# Generated by Django 4.0.3 on 2022-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
