# Generated by Django 4.0.3 on 2022-04-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketassessment',
            name='overall_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Please, evaluate the overall support:'),
        ),
        migrations.AlterField(
            model_name='ticketassessment',
            name='reaction',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Poor', 'Poor'), ('Fair', 'Fair')], max_length=9, verbose_name='Please, evaluate the SR reaction time:'),
        ),
        migrations.AlterField(
            model_name='ticketassessment',
            name='resolve',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Poor', 'Poor'), ('Fair', 'Fair')], max_length=9, verbose_name='Please, evaluate the SR resolution:'),
        ),
        migrations.AlterField(
            model_name='ticketworkflow',
            name='note',
            field=models.TextField(verbose_name='SR Note'),
        ),
        migrations.AlterField(
            model_name='ticketworkflow',
            name='typ',
            field=models.CharField(choices=[('Note', 'Note'), ('RCA', 'RCA'), ('Corrective Action', 'Corrective Action'), ('Resolution', 'Resolution')], max_length=17, verbose_name='Type:'),
        ),
    ]
