# Generated by Django 4.0.3 on 2022-04-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticketassessment_overall_remark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketFiles',
        ),
    ]
