# Generated by Django 4.0.3 on 2022-04-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_delete_ticketfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfamily',
            options={'verbose_name_plural': 'Product families'},
        ),
    ]
