# Generated by Django 4.0.3 on 2022-04-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_productfamily_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketeventlog',
            name='event',
            field=models.TextField(),
        ),
    ]
