# Generated by Django 4.0.3 on 2022-04-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_alter_ticketeventlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketassessment',
            name='overall',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=9),
        ),
        migrations.AlterField(
            model_name='ticketassessment',
            name='reaction',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=9, verbose_name='Please, evaluate the SR reaction time:'),
        ),
        migrations.AlterField(
            model_name='ticketassessment',
            name='resolve',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=9, verbose_name='Please, evaluate the SR resolution:'),
        ),
    ]
